version: '3.8'
services:
    postgres:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=root
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data