# Generated by Django 4.0.2 on 2022-02-20 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=250)),
                ('host', models.URLField(max_length=250)),
                ('github', models.URLField(max_length=250)),
                ('profileImage', models.URLField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.URLField(max_length=250)),
                ('origin', models.CharField(max_length=250)),
                ('contentType', models.CharField(max_length=125)),
                ('imageSource', models.URLField(max_length=250)),
                ('publishedDate', models.DateTimeField(auto_now=True, max_length=250)),
                ('visibility', models.CharField(choices=[('PU', 'Public'), ('FO', 'Friends-Only'), ('PR', 'Private'), ('AU', 'Authorized users')], default='PU', max_length=2)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.author')),
                ('category', models.ManyToManyField(to='service.Category')),
            ],
        ),
    ]
