# Generated by Django 4.0.2 on 2022-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1000)),
                ('displayName', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=1000)),
                ('host', models.CharField(max_length=1000)),
                ('github', models.URLField(max_length=1000)),
                ('profileImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('source', models.URLField(max_length=1000)),
                ('origin', models.CharField(max_length=1000)),
                ('contentType', models.CharField(max_length=1000)),
                ('imageSource', models.URLField(max_length=1000)),
                ('authorId', models.CharField(max_length=1000)),
                ('count', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
                ('publishedDate', models.DateTimeField(auto_now=True, max_length=1000)),
                ('visibility', models.CharField(choices=[('PU', 'Public'), ('FO', 'Friends-Only'), ('PR', 'Private'), ('AU', 'Authorized users')], default='PU', max_length=2)),
                ('unlisted', models.BooleanField(max_length=1000)),
            ],
        ),
    ]
