# Generated by Django 4.0.2 on 2022-02-20 22:59

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=service.models.generate_uuid_hex, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=service.models.generate_uuid_hex, max_length=250),
        ),
    ]
