# Generated by Django 4.0.2 on 2022-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
