# Generated by Django 4.0.2 on 2022-03-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_followrequest_object'),
        ('service', '0003_host_name_host_password'),
    ]

    operations = [
    ]
