# Generated by Django 4.0.2 on 2022-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_author_uuid_remove_post_uuid_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends-Only'), ('PRIVATE', 'Private'), ('AUTHORIZED', 'Authorized users')], default='PUBLIC', max_length=25),
        ),
    ]
