# Generated by Django 4.0.2 on 2022-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_merge_20220323_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
