# Generated by Django 4.0.2 on 2022-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('MD', 'text/markdown'), ('PT', 'text/plain'), ('B6', 'application/base64'), ('PG', 'image/png;base64'), ('JG', 'image/jpeg;base64')], default='PT', max_length=2),
        ),
    ]
