# Generated by Django 4.0.2 on 2022-02-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_post_contenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
