# Generated by Django 4.0.2 on 2022-03-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
