# Generated by Django 4.0.2 on 2022-03-01 07:23

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service', '0005_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxObject',
            fields=[
                ('id', models.CharField(default=service.models.generate_uuid_hex, editable=False, max_length=250, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=250, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.author')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
