# Generated by Django 4.0.2 on 2022-02-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
