# Generated by Django 4.0.2 on 2022-03-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_author_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500)),
                ('type', models.CharField(default='Follow', max_length=125)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='service.author')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='service.author')),
            ],
        ),
    ]
