# Generated by Django 4.0.2 on 2022-04-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_author_approved'),
        ('service', '0006_alter_followrequest_actor'),
    ]

    operations = [
    ]
