# Generated by Django 4.0.2 on 2022-03-02 18:17

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.CharField(default=service.models.generate_uuid_hex, max_length=250, primary_key=True, serialize=False),
        ),
    ]
