# Generated by Django 4.0.2 on 2022-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=125),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=125),
        ),
    ]
