# Generated by Django 4.0.2 on 2022-03-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_inboxobject'),
        ('service', '0008_alter_followrequest_id'),
    ]

    operations = [
    ]
