# Generated by Django 4.0.2 on 2022-04-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_likepost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='post',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
