# Generated by Django 4.0.2 on 2022-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_author_type_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageSource',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
