# Generated by Django 4.0.2 on 2022-03-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_merge_0006_inboxobject_0008_alter_followrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=255),
        ),
    ]
