# Generated by Django 4.0.2 on 2022-03-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_author_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='service.author'),
        ),
    ]
