# Generated by Django 4.0.2 on 2022-03-05 07:08

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_followrequest_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(default='comment', max_length=100)),
                ('id', models.CharField(default=service.models.generate_uuid_hex, max_length=250, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('content', models.CharField(max_length=500, null=True)),
                ('contentType', models.CharField(default='text/plain', max_length=50)),
                ('publishedDate', models.DateTimeField(auto_now=True, max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.post')),
            ],
        ),
    ]
