# Generated by Django 4.0.2 on 2022-04-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_likecomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.AddField(
            model_name='likecomment',
            name='post_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
