# Generated by Django 4.0.2 on 2022-04-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_likecomment_post_remove_likepost_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='post_id',
            new_name='comment_id',
        ),
    ]
