# Generated by Django 4.0.2 on 2022-04-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_followrequest_actor'),
        ('service', '0013_rename_post_id_likecomment_comment_id'),
    ]

    operations = [
    ]
